Cleaning back and updating typeORM to 0.1.0
awi2017-option1group1/Prello-back pull request #22
Opened 2017-10-17 18:37 UTC by QuentinBouygues

Changed entities joints, namings, repaired breaking changes.

2017-10-17 20:01 UTC, charlenepizzoni commented on src/bl/attachementFacade.ts
> +                        .find()
Missing join with idCard

2017-10-17 20:04 UTC, charlenepizzoni commented on src/bl/boardFacade.ts
> +                            .find()
Missing join with teamId

2017-10-18 03:12 UTC, Porquepix requested changes

2017-10-18 03:12 UTC, Porquepix commented on src/bl/boardFacade.ts
>              const board = ParamsExtractor.extract<Board>(['title', 'isPrivate'], boardReceived, boardToUpdate)
Tu peux changer les updates avec updateById qui prend un id et un objet de maj. En plus ca siplifirait ParamsExtractor.

2017-10-18 03:12 UTC, Porquepix commented on src/bl/boardFacade.ts
>              let boardToCreate = new Board()
De la même manière que pour update
```
const user = manager.create(User, {
    id: 1,
    firstName: "Timber",
    lastName: "Saw"
});
```

2017-10-18 03:12 UTC, Porquepix commented on src/bl/taskFacade.ts
> +        const taskList = await TaskListFacade.getById(taskListId)
Il y a pas moyen d'avoir ca sans faire deux fetch ? Soit en faisant directement la requête soit en préchargent la relation
`userRepository.find({ relations: ["profile", "photos", "videos"] });`

2017-10-18 03:12 UTC, Porquepix commented on src/connectionParams.ts
> -        autoSchemaSync: true,
Y a plus l'autoSync ?

2017-10-18 03:12 UTC, Porquepix commented on src/server.ts
> +connectionManager.create(connectionOptions[(ENV === 'development') ? 0 : 1]).connect().then(connection => {
Pourquoi ne pas utiliser ENV ?

2017-10-19 10:52 UTC, QuentinBouygues commented on src/connectionParams.ts
> -        autoSchemaSync: true,
Il a changé de nom, je ne l'ai pas encore commit

2017-10-19 10:53 UTC, QuentinBouygues commented on src/server.ts
> +connectionManager.create(connectionOptions[(ENV === 'development') ? 0 : 1]).connect().then(connection => {
Maintenant le tableau est de la forme : [ConnectionOption1, ConnexionOption2], avec un attribut name à l'intérieur. L'ancienne interface entrait en conflit avec les nouveaux types

2017-10-19 12:37 UTC, charlenepizzoni commented on src/bl/attachementFacade.ts
> +            let attachementToCreate = ParamsExtractor.extract<Attachement>(['type', 'URL', 'card'], attachement)
Tu prends card pour le extract et tu le reactualise la ligne d'après (attachementToCreate.card = ...)

2017-10-19 12:59 UTC, charlenepizzoni commented on src/bl/cardFacade.ts
> +            return repository.updateById(cardReceived.id, cardToSave)
Il manque peut etre des choses dans l'extractParam. Si on ne prends pas en paramère l'idList ça na sert à rien de faire un update non ?

2017-10-19 13:17 UTC, charlenepizzoni commented on src/bl/listFacade.ts
>      static async insertFromBoardId(boardId: number, list: List): Promise<List> {
Pourquoi ça s'appelle pas create ?

2017-10-19 13:26 UTC, QuentinBouygues commented on src/bl/taskFacade.ts
> +        const taskList = await TaskListFacade.getById(taskListId)
Si, mais on verra ça plus tard. Les update / create sont MaJ, les entités sont bien liées, je pense qu'il faut merge celle-là. Je MàJ les find dans une autre

2017-10-19 13:31 UTC, QuentinBouygues commented on src/bl/cardFacade.ts
> +            return repository.updateById(cardReceived.id, cardToSave)
Non, la liste est mise à jour différemment. Il faudra ajouter les routes PATCH (plus tard)

2017-10-19 13:32 UTC, QuentinBouygues commented on src/bl/listFacade.ts
>      static async insertFromBoardId(boardId: number, list: List): Promise<List> {
Ca indique qu'on l'insère avec un board ID. Mais je peux changer au besoin

2017-10-20 16:02 UTC, Porquepix approved these changes

2017-10-20 16:02 UTC, Porquepix commented
Resolve confliect then merge :+1:

2017-10-22 07:49 UTC, merged