Fix update route
awi2017-option1group1/Prello-back pull request #34
Opened 2017-10-30 23:48 UTC by QuentinBouygues

Small fix.

2017-10-31 19:19 UTC, Porquepix commented on src/app.ts
>  app.get('/users/:user_id/boards', Board.getAllFromUserId)
cammel case when possible. user_id => userId. Change it in the route too.

2017-10-31 19:20 UTC, Porquepix commented on src/bl/boardFacade.ts
> +            const board = ParamsExtractor.extract<Board>(['name', 'isPrivate'], boardReceived)
Use the param extractor v2.

2017-10-31 19:20 UTC, Porquepix commented on src/bl/boardFacade.ts
>              const repository = getManager().getRepository(Board)
Manager is useless.

2017-10-31 19:21 UTC, Porquepix requested changes
You should follow the List example for naming conventions.

2017-11-02 22:07 UTC, QuentinBouygues commented
💇‍♂️ @Porquepix

2017-11-04 16:15 UTC, Porquepix commented on src/bl/boardFacade.ts
> +            const extractor = new ParamsExtractor<Board>(params).permit(['name', 'isPrivate'])
I think name should be required for board ?

2017-11-07 09:50 UTC, Porquepix approved these changes

2017-11-07 09:53 UTC, merged