Add the ORM connection, with the database
awi2017-option1group1/Prello-back pull request #7
Opened 2017-10-01 20:24 UTC by YvesLongchamp

feat: add the typeORM connection to the database, and the entity User to work with

2017-10-01 20:33 UTC, QuentinBouygues requested changes
Globalement je valide, juste quelques commentaires mineurs. Je pars du principe qu'on accorde peu d'impotance aux fautes en anglais

2017-10-01 20:33 UTC, QuentinBouygues commented on copyStaticAssets.js
> +// shell.cp('-R', 'src/public/js/lib', 'dist/public/js/');
Pourquoi ajouter un fichier rempli de commentaires ?

2017-10-01 20:33 UTC, QuentinBouygues commented on package.json
> +    "url": "https://github.com/sahat/hackathon-starter.git"
C'est pas notre URL ça ?

2017-10-01 20:33 UTC, QuentinBouygues commented on package.json
> +  "author": "Bowden Kelly",
Same

2017-10-01 20:33 UTC, QuentinBouygues commented on src/connect.ts
> +    // userRepository.create()
Cette fonction sera décommentée prochainement ou pas ? Si c'est pas prévu autant la retirer

2017-10-01 20:44 UTC, YvesLongchamp commented on package.json
> +    "url": "https://github.com/sahat/hackathon-starter.git"
Non, je modifie ça par "Photon Team"

2017-10-01 21:35 UTC, QuentinBouygues approved these changes

2017-10-02 04:03 UTC, Porquepix requested changes
We should not mix compiled js files and ts files.
The problem comes from the `ormconfig.json`. The entities folder should be dist/entities/*.js

2017-10-02 18:50 UTC, Porquepix approved these changes

2017-10-02 18:51 UTC, merged