'petit commit'
awi2017-option1group1/Prello-back pull request #9
Opened 2017-10-04 18:49 UTC by QuentinBouygues

2017-10-04 19:23 UTC, Porquepix requested changes
Surtout du détail. Par contre enlève les fichiers de `build/dist` de ta PR :)

2017-10-04 19:23 UTC, Porquepix commented on package.json
> +    "start": "node build/dist/server.js",
Remet le strart et le serve comme avant.

2017-10-04 19:23 UTC, Porquepix commented on src/bl/errors/UserNotFoundException.ts
> +    constructor(public s: string) {
Met la variable en privée et trouve lui un nom plus explicite (genre message)

2017-10-04 19:23 UTC, Porquepix commented on src/bl/password.ts
> +        bcrypt.genSalt(10, function(err: Error, salt: string) {
Penser à gérer les erreurs et trouver un meilleur nom pour les erreurs (pas de compteur stp :))

2017-10-04 19:23 UTC, Porquepix commented on src/bl/requester.ts
> +import {User} from '../entities/user'
tslint (mettre des espaces entre le nom et les brackets)

2017-10-04 19:23 UTC, Porquepix commented on src/bl/requester.ts
> +
Saut de ligne en trop.

2017-10-04 19:23 UTC, Porquepix commented on src/bl/requester.ts
> +        if (tokenContent instanceof TokenContent  && tokenContent.hasOwnProperty('userId')) {
Je pense qu'il y a moyen de mieux gérer. Par exemple en mettant `tokenContent: TokenContent  = ...`

2017-10-04 19:23 UTC, Porquepix commented on src/routes/user/login.ts
> +
Saut de ligne en trop.

2017-10-04 19:23 UTC, Porquepix commented on src/routes/user/login.ts
> +            res.cookie('photon', cookieToSet, { maxAge: 900000, httpOnly: true })
Mettre le cookie secure.

2017-10-04 19:23 UTC, Porquepix commented on src/server.ts
> +app.post('/login', (req, res) => {
Directement faire app.post('/login', Login.authenticate)

2017-10-04 21:48 UTC, QuentinBouygues commented on src/bl/requester.ts
> +        if (tokenContent instanceof TokenContent  && tokenContent.hasOwnProperty('userId')) {
Nope, il refuse l'assignation sans savoir ce que renverra le jwt

2017-10-04 22:01 UTC, QuentinBouygues commented
on devrait y être là ^^

2017-10-05 03:13 UTC, Porquepix requested changes

2017-10-05 03:13 UTC, Porquepix commented on package.json
> +    "@types/jsonwebtoken": "^7.2.3",
Il manque la version js: jsonwebtoken.

2017-10-05 03:13 UTC, Porquepix commented on src/bl/password.ts
> +        bcrypt.genSalt(10, function(saltGenerationError: Error, salt: string) {
Je pense qu'il faut utiliser les versions sync: 
```
var salt = bcrypt.genSaltSync(saltRounds);
var hash = bcrypt.hashSync(myPlaintextPassword, salt);
```

2017-10-05 03:13 UTC, Porquepix commented on src/do_not_open_plz.ts
> +export const encryptionKey = 'prello2876387326876435'
Met process.env.ENCRYPTION_KEY || 'prello2876387326876435'. Pour que les gens n'ai pas accès à la clé.

2017-10-05 06:16 UTC, QuentinBouygues commented
💇‍♂️

2017-10-05 12:01 UTC, merged